### ISSUE TITLE
App Suggestion: [Linkwarden]

### ISSUE THREAD

**Issue by arthuragone** [caprover/one-click-apps#1022]
**Please tell us what app you'd like to see on CapRover as a one-click app.**
Linkwarden see: https://github.com/linkwarden/linkwarden
Linkwarden is a fully self-hostable, open-source collaborative bookmark manager to collect, organize and archive webpages.

**Do you know if there is any official Docker image for the app?**
Not sure, looking in the github page looks like it's a docker image but don't know how to find it within Docker website

**Comment by kgnfth** [comment]
```yml
captainVersion: 4
services:
    # Linkwarden
    $$cap_appname:
        image: ghcr.io/linkwarden/linkwarden:$$cap_linkwarden_version
        environment:
            NEXTAUTH_SECRET: $$cap_app_key
            NEXTAUTH_URL: https://$$cap_appname.$$cap_root_domain
            POSTGRES_PASSWORD: $$cap_db_pass
            DATABASE_URL: postgresql://$$cap_db_user:$$cap_db_pass@srv-captain--$$cap_appname-db:5432/$$cap_db_name
        volumes:
            - $$cap_appname-data:/data/data
        caproverExtra:
            containerHttpPort: 3000
    # Postgres
    $$cap_appname-db:
        image: postgres:12-alpine
        environment:
            POSTGRES_USER: $$cap_db_user
            POSTGRES_DB: $$cap_db_name
            POSTGRES_PASSWORD: $$cap_db_pass
        volumes:
            - $$cap_appname-db-data:/var/lib/postgresql/data
        caproverExtra:
            notExposeAsWebApp: 'true'

caproverOneClickApp:
    variables:
        - id: $$cap_linkwarden_version
          label: Linkwarden Version
          defaultValue: v2.2.1
          description: Checkout their docker page for the valid tags https://github.com/linkwarden/linkwarden/pkgs/container/linkwarden
        - id: $$cap_app_key
          label: Secret Key
          description: Secret key.
          defaultValue: $$cap_gen_random_hex(24)
        - id: $$cap_db_user
          label: Postgres database user
          defaultValue: linkwarden
          description: Enter a user for database
        - id: $$cap_db_name
          label: Postgres database name
          defaultValue: linkwarden_db
          description: Enter a databse name
        - id: $$cap_db_pass
          label: Postgres database password
          defaultValue: $$cap_gen_random_hex(24)
          description: Enter database password
    instructions:
        start: >-
            Self-hosted collaborative bookmark manager to collect, organize, and preserve webpages.
        end: >-
            Aaaand you're done! 😄
            Your service is available at https://$$cap_appname.$$cap_root_domain
    displayName: Linkwarden
    isOfficial: true
    description: Self-hosted collaborative bookmark manager to collect, organize, and preserve webpages.
    documentation: Taken from https://docs.linkwarden.app/self-hosting/installation.
```
