### ISSUE TITLE
App Suggestion:   Forgejo

### ISSUE THREAD

**Issue by jdkdev** [caprover/one-click-apps#1038]
**Please tell us what app you'd like to see on CapRover as a one-click app.**
https://forgejo.org/
github alternative

**Do you know if there is any official Docker image for the app?**
Yes, https://forgejo.org/docs/latest/admin/installation-docker/

**Comment by Sardonyx001** [comment]
@jdkdev 
This worked for me. 
```yaml
captainVersion: 4
services:
    $$cap_appname:
        image: codeberg.org/forgejo/forgejo:$$cap_forgejo_version
        volumes:
            - $$cap_appname-data:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        restart: always
        environment:
            USER_UID: 1000
            USER_GID: 1000
        ports:
            - $$cap_ssh_port:22
        caproverExtra:
            containerHttpPort: '3000'
caproverOneClickApp:
    variables:
        - id: $$cap_forgejo_version
          label: Forgejo Version
          defaultValue: '7'
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/codeberg/forgejo/tags
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_ssh_port
          label: Outside SSH port
          defaultValue: '2222'
          description: The SSH port to use when tunneling to this instance (not the actual server)
          validRegex: /^([^\s^\/])+$/
    instructions:
        start: >-
            Forgejo is a self-hosted lightweight software forge.
            Easy to install and low maintenance, it just does the job.
        end: >
            Forgejo is deployed and available as $$cap_appname.
            Since Forgejo is running inside a container, you can optionally map a port (not 22) of the host to port 22 of the container, if you want to use git commands over SSH. You can perform port mapping in your CapRover dashboard, in App Config section.

    displayName: 'Forgejo'
    isOfficial: true
    description: Forgejo is a software package for hosting software development using Git as well as bug tracking, wikis and code review
    documentation: Taken from https://forgejo.org/docs/latest/admin/installation-docker/

```
