### ISSUE TITLE
App Suggestion: Ayon

### ISSUE THREAD

**Issue by Mikfr83** [caprover/one-click-apps#1071]
I would like to deploy this open-source pipeline platform for creative studios:
https://github.com/ynput/ayon-docker
https://ayon.ynput.io/docs/admin_server_deployment

I made a yaml config, and the deployment run well.
But the Ayon server container makes this error:
[_srv-captain--ayon.1.82fg22sxvqxxuicj34joxj847_logs.txt](https://github.com/caprover/one-click-apps/files/14210884/_srv-captain--ayon.1.82fg22sxvqxxuicj34joxj847_logs.txt)

It would be great if someone could take a look!

``` yaml
captainVersion: 4
services:
    $$cap_appname-postgres:
        image: postgres:$$cap_db_version
        restart: unless-stopped
        volumes:
            - $$cap_appname-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: $$cap_db_password
            POSTGRES_DB: ayon
        expose:
            - 5432
        caproverExtra:
            notExposeAsWebApp: true

    $$cap_appname-redis:
        image: redis:alpine
        restart: unless-stopped
        volumes:
            - $$cap_appname-redis:/data
        expose:
            - 6379
        caproverExtra:
            notExposeAsWebApp: true

    $$cap_appname:
        image: ynput/ayon:$$cap_ayon_version
        restart: unless-stopped
        depends_on:
            - $$cap_appname-postgres
            - $$cap_appname-redis
        volumes:
            - $$cap_appname:/addons
            - $$cap_appname:/storage
        expose:
            - 5000
        ports:
            - 5000:5000
        caproverExtra:
            containerHttpPort: 5000

caproverOneClickApp:
    variables:
        - id: $$cap_ayon_version
          label: Ayon Version
          defaultValue: 1.0.2-20240131
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/ynput/ayon/tags
          validRegex: /^([^\\s^\\/])+$/
        - id: $$cap_db_version
          label: Postgres Version
          defaultValue: 15
          description: Check out their Docker page for the valid tags https://hub.docker.com/_/postgres/tags
          validRegex: /^([^\\s^\\/])+$/
        - id: $$cap_db_password
          label: Postgres Password
          description: Administrator password for Postgres DB.
    instructions:
        start: |-
            Ayon is open source pipeline platform for creative studios and remote teams.

            More details:
            https://github.com/ynput
            https://ayon.ynput.io/features
        end: |-
            Ayon server has been successfully deployed!
    displayName: Ayon
    isOfficial: true
    description:  Open-source pipeline platform for creative studios and remote teams.
    documentation: See https://ayon.ynput.io/features
```
