### ISSUE TITLE
App Suggestion: Qdrant

### ISSUE THREAD

**Issue by julianalsemmani** [caprover/one-click-apps#1090]
**Please tell us what app you'd like to see on CapRover as a one-click app.**
Would like to use Qdrant, which is a open-source vector database written in Rust.

**Do you know if there is any official Docker image for the app?**
Yes, they have a official docker image.
https://hub.docker.com/r/qdrant/qdrant/tags

https://qdrant.tech/documentation/quick-start/
https://github.com/qdrant/qdrant

```yaml
captainVersion: 4

services:
    '$$cap_appname':
        caproverExtra:
            dockerfileLines:
                - FROM qdrant/qdrant
                - WORKDIR /qdrant
                - EXPOSE 6333
                - CMD ["./qdrant"]
            containerHttpPort: '6333'
        volumes:
            - '$$cap_appname:/qdrant'

caproverOneClickApp:
    instructions:
        start: |-
            Qdrant is an Open-Source Vector Database and Vector Search Engine written in Rust:
            - Easy to Use API
            - Fast and Accurate
            - Filterable
            - Distributed
        end: |-
            Qdrant has been successfully deployed!
            - To change the configuration, please go to your $$cap_appname/_data/config/config.yaml file.
            - Update the information, uncomment API key and save the file.
            - Save and restart in the CapRover UI.
    displayName: Qdrant
    isOfficial: true
    description: |-
        Qdrant is an Open-Source Vector Database and Vector Search Engine written in Rust:
        - Easy to Use API
        - Fast and Accurate
        - Filterable
        - Distributed
    documentation: See https://qdrant.tech/
```

**Comment by julianalsemmani** [comment]
Just gave it a small update, so you can add the API_KEY as a env variable.

```yaml
captainVersion: 4

services:
    '$$cap_appname':
        caproverExtra:
            dockerfileLines:
                - FROM qdrant/qdrant
                - WORKDIR /qdrant
                - EXPOSE 6333
                - CMD ["./qdrant"]
            containerHttpPort: '6333'
        volumes:
            - '$$cap_appname:/qdrant'
        environment:
            - QDRANT__SERVICE__API_KEY: "$$cap_qdrant_api_key"

caproverOneClickApp:
    variables:
        - id: $$cap_qdrant_api_key
          label: Qdrant API Key
          defaultValue: "your-api-key"
          description: API Key to secure the Qdrant API & dashboard
          validRegex: /.{1,}/
    instructions:
        start: |-
            Qdrant is an Open-Source Vector Database and Vector Search Engine written in Rust:
            - Easy to Use API
            - Fast and Accurate
            - Filterable
            - Distributed
        end: |-
            Qdrant has been successfully deployed!
            - You can access the Qdrant dashboard at `http://url:6333`
            - Use the API Key you provided to secure the API & dashboard
    displayName: Qdrant
    isOfficial: true
    description: |-
        Qdrant is an Open-Source Vector Database and Vector Search Engine written in Rust:
        - Easy to Use API
        - Fast and Accurate
        - Filterable
        - Distributed
    documentation: See https://qdrant.tech/
```
