### ISSUE TITLE
App Suggestion: Postiz

### ISSUE THREAD

**Issue by iznotek** [caprover/one-click-apps#1164]
**Please tell us what app you'd like to see on CapRover as a one-click app.**

Postiz from [postiz.com](https://postiz.com)

**Do you know if there is any official Docker image for the app?**

ghcr.io/gitroomhq/postiz-app:latest

**Comment by marekbrze** [comment]
There is even Docker-compose file available from Docs https://docs.postiz.com/installation/docker-compose

```docker
services:
  postiz:
    image: ghcr.io/gitroomhq/postiz-app:latest
    container_name: postiz
    restart: always
    environment:
      # You must change these. Replace `postiz.your-server.com` with your DNS name - this needs to be exactly the URL you're accessing Postiz on.
      MAIN_URL: "https://postiz.your-server.com"
      FRONTEND_URL: "https://postiz.your-server.com"
      NEXT_PUBLIC_BACKEND_URL: "https://postiz.your-server.com/api"
      JWT_SECRET: "random string that is unique to every install - just type random characters here!"
 
      # These defaults are probably fine, but if you change your user/password, update it in the
      # postiz-postgres or postiz-redis services below.
      DATABASE_URL: "postgresql://postiz-user:postiz-password@postiz-postgres:5432/postiz-db-local"
      REDIS_URL: "redis://postiz-redis:6379"
      BACKEND_INTERNAL_URL: "http://localhost:3000"
      IS_GENERAL: "true" # Required for self-hosting.
      DISABLE_REGISTRATION: "false" # Only allow single registration, then disable signup
      # The container images are pre-configured to use /uploads for file storage.
      # You probably should not change this unless you have a really good reason!
      STORAGE_PROVIDER: "local"
      UPLOAD_DIRECTORY: "/uploads"
      NEXT_PUBLIC_UPLOAD_DIRECTORY: "/uploads"
    volumes:
      - postiz-config:/config/
      - postiz-uploads:/uploads/
    ports:
      - 5000:5000
    networks:
      - postiz-network
    depends_on:
      postiz-postgres:
        condition: service_healthy
      postiz-redis:
        condition: service_healthy
 
  postiz-postgres:
    image: postgres:17-alpine
    container_name: postiz-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postiz-password
      POSTGRES_USER: postiz-user
      POSTGRES_DB: postiz-db-local
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - postiz-network
    healthcheck:
      test: pg_isready -U postiz-user -d postiz-db-local
      interval: 10s
      timeout: 3s
      retries: 3
  postiz-redis:
    image: redis:7.2
    container_name: postiz-redis
    restart: always
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - postiz-redis-data:/data
    networks:
      - postiz-network
 
 
volumes:
  postgres-volume:
    external: false
 
  postiz-redis-data:
    external: false
 
  postiz-config:
    external: false
 
  postiz-uploads:
    external: false
 
networks:
  postiz-network:
    external: false
```

**Comment by marekbrze** [comment]
I think that finally this version of Captain Definition worked for me:

```yaml
captainVersion: 4
services:
  $$cap_appname:
    image: ghcr.io/gitroomhq/postiz-app:latest
    restart: always
    environment:
      # You must change these. Replace `postiz.your-server.com` with your DNS name - this needs to be exactly the URL you're accessing Postiz on.
      MAIN_URL: https://$$cap_appname.$$cap_root_domain
      FRONTEND_URL: https://$$cap_appname.$$cap_root_domain
      NEXT_PUBLIC_BACKEND_URL: https://$$cap_appname.$$cap_root_domain/api
      JWT_SECRET: $$cap_jwt_token

      # These defaults are probably fine, but if you change your user/password, update it in the
      # postiz-postgres or postiz-redis services below.
      DATABASE_URL: "postgresql://$$cap_db_user:$$cap_db_password@srv-captain--$$cap_appname-db:5432/$$cap_appname-db"
      REDIS_URL: "redis://srv-captain--$$cap_appname-redis:6379"
      BACKEND_INTERNAL_URL: srv-captain--$$cap_appname
      IS_GENERAL: "true" # Required for self-hosting.
      DISABLE_REGISTRATION: "false" # Only allow single registration, then disable signup
      # The container images are pre-configured to use /uploads for file storage.
      # You probably should not change this unless you have a really good reason!
      STORAGE_PROVIDER: "local"
      UPLOAD_DIRECTORY: "/uploads"
      NEXT_PUBLIC_UPLOAD_DIRECTORY: "/uploads"
    volumes:
      - $$cap_appname-config:/config/
      - $$cap_appname-uploads:/uploads/
    ports:
      - 5000:5000
    depends_on:
      - $$cap_appname-db
      - $$cap_appname-redis
    caproverExtra:
      containerHttpPort: 5000

  $$cap_appname-db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: $$cap_db_password
      POSTGRES_USER: $$cap_db_user
      POSTGRES_DB: $$cap_appname-db
    volumes:
      - $$cap_appname-db-data:/var/lib/postgresql/data
    caproverExtra:
      notExposeAsWebApp: "true"

  $$cap_appname-redis:
    image: redis:7.2
    restart: always
    volumes:
      - $$cap_appname-redis-data:/data
    caproverExtra:
      notExposeAsWebApp: "true"

caproverOneClickApp:
  variables:
    - id: $$cap_db_user
      label: Database user
      defaultValue: admin
      validRegex: /^([a-zA-Z0-9])+$/

    - id: $$cap_db_password
      label: Database Password
      defaultValue: $$cap_gen_random_hex(16)
      description: Password for the Postgres database.

    - id: $$cap_jwt_token
      label: Postiz JWT Token
      defaultValue: $$cap_gen_random_hex(16)
      description: Postiz JWT Token

  instructions:
    start: >-
      Deploy started
    end: >
      App is ready!
  displayName: Postiz
  isOfficial: false
  description: Postiz social media platform
  documentation: https://docs.postiz.com/introduction
```

**Comment by ThcDelux3** [comment]
This works for me
```
captainVersion: 4
services:
    $$cap_appname:
        image: ghcr.io/gitroomhq/postiz-app:$$cap_POSTIZ_VERSION
        caproverExtra:
            containerHttpPort: 5000
            websocketSupport: 'true'
        environment:
            MAIN_URL: 'https://$$cap_appname.$$cap_root_domain'
            FRONTEND_URL: 'https://$$cap_appname.$$cap_root_domain'
            NEXT_PUBLIC_BACKEND_URL: 'https://$$cap_appname.$$cap_root_domain/api'
            JWT_SECRET: $$cap_JWT_SECRET
            DATABASE_URL: 'postgresql://postiz:$$cap_POSTGRES_PASSWORD@srv-captain--$$cap_appname-postgres:5432/postiz-db'
            REDIS_URL: 'redis://srv-captain--$$cap_appname-redis:6379'
            BACKEND_INTERNAL_URL: 'http://localhost:3000'
            IS_GENERAL: 'true' # Required for self-hosting.
            DISABLE_REGISTRATION: 'false'
            STORAGE_PROVIDER: 'local'
            UPLOAD_DIRECTORY: '/uploads'
            NEXT_PUBLIC_UPLOAD_DIRECTORY: '/uploads'
        volumes:
            - $$cap_appname-config:/config/
            - $$cap_appname-uploads:/uploads/
        depends_on:
            - $$cap_appname-postgres
            - $$cap_appname-redis

    $$cap_appname-postgres:
        image: postgres:$$cap_POSTGRES_VERSION
        caproverExtra:
            notExposeAsWebApp: 'true'
        environment:
            POSTGRES_PASSWORD: $$cap_POSTGRES_PASSWORD
            POSTGRES_USER: postiz
            POSTGRES_DB: postiz-db
        volumes:
            - $$cap_appname-postgres-data:/var/lib/postgresql/data

    $$cap_appname-redis:
        image: redis:$$cap_REDIS_VERSION
        caproverExtra:
            notExposeAsWebApp: 'true'
        volumes:
            - $$cap_appname-redis-data:/data

caproverOneClickApp:
    variables:
        - id: $$cap_POSTIZ_VERSION
          label: Postiz Version
          defaultValue: 'v2.8.3'
          description: The version of Postiz docker image (from https://github.com/gitroomhq/postiz-app/pkgs/container/postiz-app)
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_JWT_SECRET
          label: JWT Secret
          defaultValue: $$cap_gen_random_hex(64)
          description: A random string that should be unique for every installation. This is used to secure your JWT auth tokens.
        - id: $$cap_POSTGRES_VERSION
          description: Postgres version (from https://hub.docker.com/_/postgres?tab=tags)
          label: Postgres Version
          defaultValue: 17-alpine
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_POSTGRES_PASSWORD
          defaultValue: 'postiz'
          description: This is the PostgreSQL password for user 'postiz'. Please change it.
          label: Postgres Password
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_REDIS_VERSION
          description: Redis version (from https://hub.docker.com/_/redis/tags)
          label: Redis Version
          defaultValue: 8.0.0
          validRegex: /^([^\s^\/])+$/
    instructions:
        start: |-
            Postiz helps you manage all of your social media accounts.

            - Schedule social media and articles
            - Generate posts with AI
            - Exchange or buy posts from other members on the marketplace
        end: |-
            Postiz is deployed and available as $$cap_appname. Some additional steps are required:
              - Postiz requires HTTPS, so you will need to enable it for this app. If using HTTPS is not possible, add the following environment variable to $$cap_appname: NOT_SECURED=true.
              - You will need to configure your providers. Visit https://docs.postiz.com/providers for more information on how to configure them.

            See https://docs.postiz.com/configuration/reference for a full list of configuration options.
    displayName: Postiz
    isOfficial: true
    description: Postiz helps you manage all of your social media accounts.
    documentation: Taken from https://docs.postiz.com/installation/docker-compose.
```
