### ISSUE TITLE
App Suggestion: [Papermerge]

### ISSUE THREAD

**Issue by FJLendinez** [caprover/one-click-apps#331]
**Please tell us what app you'd like to see on CapRover as a one-click app.**
Papermerge is a document management system designed to work with scanned documents. As well as OCR with full text search, it provides the look and feel of major modern file browsers, with tags and hierarchical structure for files and folders, so that you can organize your documents in a similar way to Dropbox (via web) or Google Drive (but with tags and other cool features).

**Do you know if there is any official Docker image for the app?**
Yes, it is. And I create a minimal viable captain definition as a stating point. 

```
captainVersion: 4
services:
  $$cap_appname-papermerge:
    image: eugenci/papermerge
    ports:
      - "8000:8000"
    depends_on:
      - $$cap_appname-db
    volumes:
      - $$cap_appname-papermerge-media:/opt/media
      - $$cap_appname-papermerge-queue:/opt/app/queue
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: dbname
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
  $$cap_appname-db:
    image: postgres:12.3
    volumes:
      - $$cap_appname-db-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: dbname
  $$cap_appname-worker:
    image: eugenci/papermerge-worker
    volumes:
      - $$cap_appname-worker-media:/opt/media
      - $$cap_appname-worker-queue:/opt/app/queue
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: dbname
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432      
caproverOneClickApp:
    instructions:
        start: >-
            asdf
        end: >
            asdf
    displayName: PaperMerge
    isOfficial: false
    description: Papermerge is a document management system designed to work with scanned documents. As well as OCR with full text search, it provides the look and feel of major modern file browsers, with tags and hierarchical structure for files and folders, so that you can organize your documents in a similar way to Dropbox (via web) or Google Drive (but with tags and other cool features).
    documentation: https://papermerge.readthedocs.io/en/latest/
```
