### ISSUE TITLE
[Deployment Issue] Problem while creating one-click-app for JellyFin

### ISSUE THREAD

**Issue by dramikei** [caprover/one-click-apps#427]
I was creating an one-click app for Caprover using linuxserver.io's docker-compose from [here](https://hub.docker.com/r/linuxserver/jellyfin)

But while deploying to test the yml I get the following error:

`Failed: Error: Host or container port is missing`

[Screenshot](https://imgur.com/a/y4UStGm)

captain-captain log:

```
GET /api/v2/user/oneclick/repositories 304 4.594 ms - -
GET /api/v2/user/oneclick/template/list 304 15.920 ms - -
GET /api/v2/user/system/info 304 3.036 ms - -
May 7th 2021, 6:24:54.059 pm    Registering app started: test5
May 7th 2021, 6:24:54.189 pm    Building docker image. This might take a few minutes...
May 7th 2021, 6:24:54.914 pm    Ensure service inited and Updated for: test5
May 7th 2021, 6:24:54.915 pm    Check if service is running: srv-captain--test5
May 7th 2021, 6:24:54.920 pm    Creating service srv-captain--test5 with default image, we will update image later
May 7th 2021, 6:24:55.025 pm    Updating service srv-captain--test5 with image img-captain-test5:0
May 7th 2021, 6:24:57.062 pm    Updating Load Balancer - ServiceManager
May 7th 2021, 6:24:57.062 pm    Locking NGINX configuration reloading...
May 7th 2021, 6:24:57.078 pm    SUCCESS: UNLocking NGINX configuration reloading...
May 7th 2021, 6:24:57.079 pm    sendReloadSignal...
May 7th 2021, 6:24:57.082 pm    Kill HUP Container: c6e214cb6d42abd06b43c12824f63e846b96e35edbcbbcfc7235a408be9df29e
May 7th 2021, 6:24:57.213 pm    AppName is saved: test5
POST /api/v2/user/apps/appDefinitions/register 200 3156.653 ms - 61
GET /api/v2/user/apps/appDefinitions 200 4.093 ms - 18599
May 7th 2021, 6:24:58.504 pm    Updating app started: test5
May 7th 2021, 6:24:58.511 pm    Error: Host or container port is missing
Error: Host or container port is missing
    at Function.createError (/usr/src/app/built/api/ApiStatusCodes.js:8:16)
    at /usr/src/app/built/datastore/AppsDataStore.js:71:56
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
POST /api/v2/user/apps/appDefinitions/update 200 8.136 ms - 75
May 7th 2021, 6:25:00.060 pm    Pruning containers...
```

Log [screenshot](https://imgur.com/a/4g6jQia)

The YAML I used is as follows:
```yaml
captainVersion: 4
services:
    $$cap_appname:
        image: ghcr.io/linuxserver/jellyfin
        environment:
            PUID: $$cap_puid
            PGID: $$cap_pgid
            TZ: $$cap_tz
            JELLYFIN_PublishedServerUrl: '$$cap_appname.$$cap_root_domain'
        volumes:
            - $$cap_appname-config:/config
            - $$cap_appname-tvshows:/data/tvshows
            - $$cap_appname-movies:/data/movies
        caproverExtra:
            containerHttpPort: '8096'
            notExposeAsWebApp: 'true'
        ports:
            - 7359:7359/udp
            - 1900:1900/udp
caproverOneClickApp:
    variables:
        - id: '$$cap_puid'
          label: Jellyfin UserID
          defaultValue: 1000
          description: UserID used by JellyFin to avoid permission problems, please refer to docs- https://github.com/linuxserver/docker-jellyfin#Parameters
          validRegex: /[0-9]/
        - id: '$$cap_pgid'
          label: Jellyfin GroupID
          defaultValue: 1000
          description: GroupID used by JellyFin to avoid permission problems, please refer to docs- https://github.com/linuxserver/docker-jellyfin#Parameters
          validRegex: /[0-9]/
        - id: '$$cap_tz'
          label: Time Zone
          defaultValue: Asia/Kolkata
          description: Get yours from https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
          validRegex: /.{1,}/
    instructions:
        start: |-
            Jellyfin is a Free Software Media System that puts you in control of managing and streaming your media.
            It is an alternative to the proprietary Emby and Plex, to provide media from a dedicated server to end-user devices via multiple apps.

            For more details visit- https://github.com/jellyfin/jellyfin

            PS. It might not work with RPi, or atleast, you wont be able to use OpenMax or V4L2 because Caprover idnores 'devices' parameters
        end: |-
            Jellyfin has been successfully deployed!
    displayName: Jellyfin
    isOfficial: false
    description: A free media streaming alternative to Plesk.
    documentation: See https://github.com/linuxserver/docker-jellyfin
```

Upon investigating the log, I found that in the [AppsDataStore.ts](https://github.com/caprover/caprover/blob/master/src/datastore/AppsDataStore.ts) The error is raised via an if-else block:

```ts
if (app.ports) { ... }
else {
    throw ApiStatusCodes.createError(ApiStatusCodes.STATUS_ERROR_GENERIC, `Host or container port is missing`);
}
```

I am not sure if the issue is because my YML is being parsed wrongly due to some error or an issue in Caprover.
