### ISSUE TITLE
[question] Is there any way to add shm_size? 

### ISSUE THREAD

**Issue by amjed-ali-k** [caprover/one-click-apps#465]
For use apps like firefox,  it requires atleast 1GB shm size.
Is there any way to add shm_size property to the container. 

```yml
    ports:
      - 3000:3000
    shm_size: "1gb"
    restart: unless-stopped
````

**Comment by githubsaturn** [comment]
As mentioned in the readme:
> - Other than `image`, `environment`, `ports`, `volumes`, `depends_on`, and `hostname`, other parameters are currently being ignored by CapRover. If you need a particular parameter, please file an issue, and we'll add it to the respected list.

[Looks like](https://github.com/moby/moby/issues/26714) the config is not even exposed through `docker service update` natively.

Probably, post deployment you can use something like this as [config override](https://caprover.com/docs/service-update-override.html). But nothing built-in in one-click app.
```
TaskTemplate:
  ContainerSpec:
    Mounts:
      Type: tmpfs
      Target: /dev/shm
      TmpfsOptions:
            SizeBytes: 2000000000
```
