### ISSUE TITLE
Minio one click app web UI not accessible by default

### ISSUE THREAD

**Issue by Handfish** [caprover/one-click-apps#475]
The Minio web UI is inaccessible at the moment. I am able to interact with the server via the `mc` cli tool they provide.
I'm not quite sure how to fix it - I'm not super savy on IT or DevOps related tasks.

Also, the environment variables are old - I've updated them and tried to deploying with the admin console binded to a port. Here is my template file at the moment. 

For external access, do I need to port map and unblock the admin console port (ie :9001) in the firewall to access the web UI?
```
captainVersion: 4
services:
    $$cap_appname:
        volumes:
            - $$cap_appname-db-data:/data
            - $$cap_appname-config-data:/root/.minio
        restart: always
        expose:
            - '9000'
            - '9001'
        environment:
            MINIO_ROOT_USER: $$cap_access_key
            MINIO_ROOT_PASSWORD: $$cap_secret_key
        caproverExtra:
            containerHttpPort: '9000'
            dockerfileLines:
                - FROM minio/minio:$$cap_minio_version
                - CMD ["minio", "server", "/data", "--console-address", ":9001"]
caproverOneClickApp:
    variables:
        - id: $$cap_minio_version
          label: Minio Version
          defaultValue: latest
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/minio/minio/tags/
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_access_key
          label: Minio Access Key
          defaultValue: ''
          description: Username to access minio server
          validRegex: /.{5,}/
        - id: $$cap_secret_key
          label: Minio Secret Key
          defaultValue: ''
          description: Password to access minio server
          validRegex: /.{8,}/
    instructions:
        start: >-
            Minio is an object storage server released under Apache License v2.0. It is compatible with Amazon S3 cloud storage service. It is best suited for storing unstructured data such as photos, videos, log files, backups and container / VM images. Size of an object can range from a few KBs to a maximum of 5TB. Minio server is light enough to be bundled with the application stack, similar to NodeJS, Redis and MySQL. 
            This one click app deploy one single instance of minio. If you are deploying minio in a high demand production environment, you should consider deploying multiple instances of minio. See minio docs for more details. https://www.minio.io/
        end: Minio is deployed and available as $$cap_appname
    displayName: ''
    isOfficial: true
    description: MinIO is a cloud storage server compatible with Amazon S3
    documentation: Taken from https://hub.docker.com/r/minio/minio
```
