### ISSUE TITLE
App Suggestion: AppWrite

### ISSUE THREAD

**Issue by nileshtrivedi** [caprover/one-click-apps#551]
[AppWrite](https://appwrite.io/) is a self hosted backend as a service.

They provide these instruction for deploying via Docker:

```
docker run -it --rm \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \
    --entrypoint="install" \
    appwrite/appwrite:0.11.0
```

**Comment by githubsaturn** [comment]
There was an attempt to add AppWrite but it was abandoned by the author: https://github.com/caprover/one-click-apps/pull/340/files

Feel free to pick up where they left off.

Also, it looks like the one click app WIP above has a lot more parameters than the Docker run command you've suggested. 


The one you've suggested can be simply done like this:
```yaml
captainVersion: 4
services:
    $$cap_appname:
        volumes:
            - $$cap_appname-data:/usr/src/code/appwrite
            - /var/run/docker.sock:/var/run/docker.sock
        caproverExtra:
            dockerfileLines:
                - FROM appwrite/appwrite:$$cap_version
                - ENTRYPOINT install
caproverOneClickApp:
    variables:
        - id: $$cap_version
          label: Version Tag
          description: 'Check out their Docker page for the valid tags'
          defaultValue: '0.11.0'
          validRegex: /^([^\s^\/])+$/
    instructions:
        start: >-
            something.
        end: >-
            something.
    displayName: SomeName
    isOfficial: true
    description: something
    documentation: Taken from something
```
