### ISSUE TITLE
App Suggestion: Listmonk

### ISSUE THREAD

**Issue by sandoche** [caprover/one-click-apps#599]
I would love to have Listmonk in Caprover:
https://listmonk.app/

**Comment by sandoche** [comment]
I started this but didn't manage to make it work, feel free to continue it

```yml
captainVersion: 4

version: "3.7"

services:
    $$cap_appname-postgres:
        image: postgres:12
        volumes:
            - $$cap_appname-postgres-data:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_USER: $$cap_postgre_username
            POSTGRES_PASSWORD: $$cap_postgre_password
            POSTGRES_DB: $$cap_postgre_db_name
        caproverExtra:
            notExposeAsWebApp: 'true'
    '$$cap_appname':
        image: listmonk/listmonk:$$cap_version
        environment:
            TZ: Etc/UTC
            LISTMONK_db__host: srv-captain--$$cap_appname-postgres
            LISTMONK_db__database: $$cap_postgre_db_name
            LISTMONK_db__user: $$cap_postgre_username
            LISTMONK_db__password: $$cap_postgre_password
            LISTMONK_db__ssl_mode: $$cap_postgre_ssl_mode
            LISTMONK_app__admin_username: $$cap_listmonk_admin_username
            LISTMONK_app__admin_password: $$cap_listmonk_admin_password
            LISTMONK_app__address: $$cap_appname.$$cap_root_domain
        caproverExtra:
            containerHttpPort: '9000'
        volumes:
            - $$cap_appname:/
        command: 
            - ./listmonk --install
        depends_on:
            - $$cap_appname-postgres

caproverOneClickApp:
    variables:
        - id: '$$cap_version'
          label: Listmonk Version
          defaultValue: 'v2.0.0'
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/listmonk/listmonk/tags
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_postgre_db_name
          label: PostgreSQL Database name
          description: ''
          defaultValue: 'listmonk'
          validRegex: /.{1,}/
        - id: $$cap_postgre_username
          label: PostgreSQL username
          defaultValue: 'listmonk'
          description: ''
          validRegex: /.{1,}/
        - id: $$cap_postgre_password
          label: PostgreSQL Password
          description: ''
          defaultValue: 'listmonk'
          validRegex: /.{1,}/
        - id: $$cap_postgre_ssl_mode
          label: PostgreSQL SSL Mode
          description: ''
          defaultValue: 'disable'
          validRegex: /.{1,}/
        - id: $$cap_listmonk_admin_username
          label: Listmonk Admin Username
          description: ''
          defaultValue: 'listmonk'
          validRegex: /.{1,}/
        - id: $$cap_listmonk_admin_password
          label: Listmonk Admin Password
          description: ''
          defaultValue: 'listmonk'
          validRegex: /.{1,}/  
    instructions:
        start: |-
            $$cap_appname installation will start
            
        end: |-
            $$cap_appname is deployed
    displayName: Listmonk
    isOfficial: true ## Only if all images used here are official or from a trusted source.
    description: High performance, self-hosted newsletter and mailing list manager with a modern dashboard 
    documentation: This docker-compose is taken https://github.com/knadh/listmonk
```
