### ISSUE TITLE
App Suggestion: Rclone

### ISSUE THREAD

**Issue by viperadnan-git** [caprover/one-click-apps#623]
# Rclone with WebUI
- Rclone Webpage
https://rclone.org
- Official Docker Image
https://hub.docker.com/r/rclone/rclone

```yml
rclone_rclone:
    image: rclone/rclone
    container_name: rclone_rclone
    restart: always
    command: rcd --rc-web-gui --rc-addr :5572 --rc-user jsmith --rc-pass mypassword
    ports:
      - "5572:5572"
    volumes:
      - /home/jsmith/docker/rclone_rclone:/config/rclone
      - /home/jsmith/docker/rclone_rclone:/logs
    environment:
      - PHP_TZ=Europe/London
      - PUID=1000
      - PGID=1000
```

**Additional information from official forum**
https://forum.rclone.org/t/how-to-set-up-rclone-webgui-server-as-a-docker-container/14330
