### ISSUE TITLE
App issue: How to set memory limit? 

### ISSUE THREAD

**Issue by hermesalvesbr** [caprover/one-click-apps#735]
I already have some one click app made by me, very practical to do. Thank you for existing!

I would like to know if there is a way to limit the memory usage and processing of the app via yaml. I already tried this:

```
        deploy:
            resources:
                limits:
                    cpus: 1
                    memory: 1G
                reservations:
                    cpus: 0.50
                    memory: 512M
        Resources:
          Limits:
            MemoryBytes: 104857600
            NanoCPUs: 2000000000
          Reservations:
            MemoryBytes: 104857600
            NanoCPUs: 2000000000
```
Inside myApp.yml and didn't work. Another way to limit the oneclick app memory and cpu utilizitaion?
