### ISSUE TITLE
App Suggestion: SFTPGo

### ISSUE THREAD

**Issue by sebastian-b00** [caprover/one-click-apps#851]
**Please tell us what app you'd like to see on CapRover as a one-click app.**
SFTPGo
https://github.com/drakkan/sftpgo

**Do you know if there is any official Docker image for the app?**
Yes, https://hub.docker.com/r/drakkan/sftpgo
also https://github.com/users/drakkan/packages/container/package/sftpgo

This maybe can help:

```
captainVersion: 4
services:
    '$$cap_appname':
        image: drakkan/sftpgo:$$cap_app_version
        ports:
            - $$cap_sftp_port:2022
        volumes:
            - '$$cap_appname-data:/srv/sftpgo'
            - '$$cap_appname-home:/var/lib/sftpgo'
        caproverExtra:
            containerHttpPort: '8080'
caproverOneClickApp:
    variables:
        - id: '$$cap_app_version'
          label: SFTPGo Version
          defaultValue: 'v2.4.3'
          description: Check the Docker page for valid tags https://hub.docker.com/r/drakkan/sftpgo/tags
        - id: '$$cap_sftp_port'
          label: SFTP port
          defaultValue: '2022'
          description: The port that will be exposed for SFTP (this is NOT the HTTP port).
    instructions:
        start: |-
            A SFTP server and more.
            Github repository: https://github.com/drakkan/sftpgo
        end: |-
            SFTPGo has been successfully deployed!
            Please wait some seconds and then you can go to the Admin interface from 
            http://$$cap_appname.$$cap_root_domain/web/admin
    displayName: SFTPGo
    isOfficial: true
    description: A SFTP server and more.
```
