### ISSUE TITLE
App Suggestion: [RustDesk]

### ISSUE THREAD

**Issue by cvladan** [caprover/one-click-apps#896]
**Please tell us what app you'd like to see on CapRover as a one-click app.**

[RustDesk](https://rustdesk.com/)  
Open source remote desktop software aka The Open Source TeamViewer Alternative

**Do you know if there is any official Docker image for the app?**
https://github.com/rustdesk/rustdesk-server

**Comment by wraythezw** [comment]
I'll second this!

**Comment by g2david** [comment]
i vote for it

**Comment by brenner-tobias** [comment]
+1

**Comment by skyelillith** [comment]
+1

Is this maybe in someone's 3rd party Repository maybe?

**Comment by githubsaturn** [comment]
I don't know how this image is supposed to work, but it's fairly simple based on their instructions. Maybe this works?

* In one click apps search for `TEMPLATE` and select that.
Paste this template:
```yml
captainVersion: 4
services:
    $$cap_appname-hbbs:
        image: rustdesk/rustdesk-server:$$cap_rustdesk_version
        command: hbbs -r $$cap_appname.$$cap_root_domain:21117
        volumes:
            - $$cap_appname-data:/root
        ports:
            - '21115:21115'
            - '21116:21116'
            - '21118:21118'
        depends_on:
            - $$cap_appname-hbbr
        restart: unless-stopped
    $$cap_appname-hbbr:
        image: rustdesk/rustdesk-server:$$cap_rustdesk_version
        command: hbbr
        volumes:
            - $$cap_appname-data:/root
        ports:
            - '21117:21117'
            - '21119:21119'
        restart: unless-stopped

caproverOneClickApp:
    variables:
        - id: $$cap_rustdesk_version
          label: RustDesk Version
          defaultValue: 'latest'
          description: 'Select the version of RustDesk server to deploy. Default is "latest".'
    instructions:
        start: |-
            This CapRover One-Click App deploys RustDesk server with hbbs and hbbr services.
            Before proceeding, ensure you have the correct version selected for deployment.
        end: |-
            RustDesk Server has been successfully deployed! Access the server on the specified ports through your CapRover root domain.
    displayName: RustDesk Server
    isOfficial: false
    description: Deploy RustDesk server with hbbs and hbbr services on CapRover.
    documentation: This configuration is adapted for CapRover from the official RustDesk Docker images.

volumes:
    $$cap_appname-data: {}

```
